### ISSUE TITLE
negative expo

### ISSUE THREAD

**Issue by KiWy86** [Marc-Anderson/multirotor-rate-converter#5]
hi thanks for the conveter.

i would like to ask, if its possible to make the converter work with negative Expo values?

**Comment by Marc-Anderson** [comment]
Hey @KiWy86, glad to have contributed something useful to the community! 😃 I know you can set negative expo in a radio but is that even possible in any of the supported rate types? Don't think I have ever tried it.

**Comment by FoxvibesFPV** [comment]
Hey @Marc-Anderson 
Your converter is very usefull for the community. I know a lot  people using it, and suggesting to use it.
It's awesome, because you can just hit convert. While in other converters you need to thinker manually on your curve, till they match....

Yes negative expo is possible, at least under actual rates you can go down to -1 expo
Setting negative expo, helps me to have more linear rates.

**Comment by Marc-Anderson** [comment]
Sorry for the extreme delay, this project has taken a back seat for a while.

Based on the below documentation, it appears that negative expo values in Betaflight's `actual` rates is not supported. I don't have access to testing so feel free to reply with additional details if I'm mistaken. This issue is closed unless further information is provided to demonstrate otherwise.

1. The initial [actual rates proposal](https://github.com/betaflight/betaflight/pull/9495) in Betaflight does not indicate negative expo is possible.
2. The [Desmos calculator](https://www.desmos.com/calculator/r5pkxlxhtb) referenced in the Betaflight docs limit `actual` expo between 0 and 1.
    * This is mentioned in the [4.3 move to make actual rates default](https://github.com/betaflight/betaflight/pull/10724).
    * It is also noted in the [Betaflight 4.3 tuning guide](https://betaflight.com/docs/wiki/tuning/4-3-Tuning-Notes#actual-rates-as-the-new-betaflight-default)
3. The [Betaflight/Cleanflight Control Rate Profile](https://github.com/betaflight/betaflight/blob/9730f9ee16ba645c157d3fdf0a02784ac4f99b2d/src/main/fc/controlrate_profile.c#L69) and [Betaflight/Cleanflight Flight Control Config](https://github.com/betaflight/betaflight/blob/9730f9ee16ba645c157d3fdf0a02784ac4f99b2d/src/main/config/config.c#L201) limits actual expo to 100 units(1.0).
